openai:
  api:
    url: https://api.openai.com/v1/chat/completions # Using the Chat Completions endpoint
    key: YOUR_OPENAI_API_KEY # !! Replace with your actual key !!
    model: gpt-3.5-turbo # Or gpt-4, or other suitable model
    timeout: 10000 # Timeout in milliseconds for the API call
    max-tokens: 500 # Max tokens for the AI response
    temperature: 0.7 # Controls randomness (0.0 to 2.0)

server:
  port: 8080

logging:
  level:
    com.example: DEBUG # To see incoming requests (optional)
    org.springframework.web.reactive.function.client: DEBUG  # To see outgoing requests (optional)